"""Make indexes

Revision ID: f44135d617c0
Revises: 963e63fa66b3
Create Date: 2026-02-08 12:21:38.280075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44135d617c0'
down_revision: Union[str, Sequence[str], None] = '963e63fa66b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_owner_id'), 'companies', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documents_employee_id'), 'documents', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_index(op.f('ix_documents_employee_id'), table_name='documents')
    op.drop_index(op.f('ix_companies_owner_id'), table_name='companies')
    # ### end Alembic commands ###
